[project]
name = "zinc_fusion_v15"
requires-python = ">=3.10,<3.15"
version = "0.1.0"
dependencies = [
    "dagster",
    "duckdb>=0.9.0",
    "pandas",
    "matplotlib",
]

[dependency-groups]
dev = [
    "dagster-webserver",
    "pytest",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.dagster]
module_name = "quickstart_etl.definitions"
code_location_name = "zinc_fusion_v15"
