[project]
name = "zinc_fusion_v15"
requires-python = ">=3.10,<3.13"
version = "0.1.0"
dependencies = [
    "dagster>=1.11,<2.0",
    "duckdb>=1.4.2,<2.0",
    "numpy>=2.0,<3.0",
    "pandas>=2.0,<3.0",
    "matplotlib>=3.8,<4.0",
    "dash>=2.0",
    "dash-bootstrap-components>=1.0",
    "plotly>=5.0",
    "mlflow>=2.0",
    "autogluon>=1.4,<2.0",
]

[dependency-groups]
dev = [
    "dagster-webserver",
    "pytest",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.dagster]
module_name = "quickstart_etl.definitions_new"
code_location_name = "zinc_fusion_v15"
