apiVersion: 1

datasources:
  - name: ZINC-Fusion-Prisma
    type: postgres
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}
    jsonData:
      sslmode: require
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1700
      timescaledb: false
    isDefault: true
    editable: true
