-- Drift reconciliation — safe items only
-- Applied via migrate resolve --applied (never migrate deploy)
-- Skipped: REAL→DOUBLE widening (intentional, tuple limit)
-- Skipped: oof_core_1d (schema.prisma needs manual correction)
-- Skipped: mkt.futures_1d column drops (source table protection)
-- Categories applied: A (renames), C (matrix_1d drops),
--   D (column adds), G (index changes)

-- ---------------------------------------------------------------------------
-- 1. CONSTRAINT RENAMES (Category A — 13 statements)
-- ---------------------------------------------------------------------------

ALTER TABLE "alt"."econ_news_event" RENAME CONSTRAINT "econ_news_pkey" TO "econ_news_event_pkey";

ALTER TABLE "alt"."executive_actions_event" RENAME CONSTRAINT "executive_actions_pkey" TO "executive_actions_event_pkey";

ALTER TABLE "alt"."ice_enforcement_event" RENAME CONSTRAINT "ice_enforcement_pkey" TO "ice_enforcement_event_pkey";

ALTER TABLE "alt"."policy_news_event" RENAME CONSTRAINT "policy_news_pkey" TO "policy_news_event_pkey";

ALTER TABLE "alt"."profarmer_news_event" RENAME CONSTRAINT "profarmer_news_pkey" TO "profarmer_news_event_pkey";

ALTER TABLE "alt"."tariff_deadlines_static" RENAME CONSTRAINT "tariff_deadlines_pkey" TO "tariff_deadlines_static_pkey";

ALTER TABLE "analytics"."latest_price" RENAME CONSTRAINT "zl_latest_pkey" TO "latest_price_pkey";

ALTER TABLE "analytics"."price_15m" RENAME CONSTRAINT "zl_price_15m_pkey" TO "price_15m_pkey";

ALTER TABLE "analytics"."price_5m" RENAME CONSTRAINT "zl_price_5m_pkey" TO "price_5m_pkey";

ALTER TABLE "features"."intel_drops_event" RENAME CONSTRAINT "intel_drops_pkey" TO "intel_drops_event_pkey";

ALTER TABLE "training"."model_runs_event" RENAME CONSTRAINT "model_runs_pkey" TO "model_runs_event_pkey";

ALTER TABLE "training"."realized_volatility_1d" RENAME CONSTRAINT "realized_volatility_pkey" TO "realized_volatility_1d_pkey";

ALTER TABLE "training"."volatility_surface_1d" RENAME CONSTRAINT "volatility_surface_pkey" TO "volatility_surface_1d_pkey";

-- ---------------------------------------------------------------------------
-- 2. INDEX OPERATIONS (Category G — 11 statements, excluding oof_core_1d)
-- ---------------------------------------------------------------------------

DROP INDEX "ops"."idx_pipeline_alerts_created_at";

CREATE INDEX "idx_pipeline_alerts_created_at" ON "ops"."pipeline_alerts"("created_at");

ALTER INDEX "alt"."profarmer_news_row_hash_key" RENAME TO "profarmer_news_event_row_hash_key";

ALTER INDEX "alt"."profarmer_news_url_key" RENAME TO "profarmer_news_event_url_key";

ALTER INDEX "alt"."tariff_deadlines_deadline_name_deadline_date_key" RENAME TO "tariff_deadlines_static_deadline_name_deadline_date_key";

ALTER INDEX "analytics"."event_probabilities_1d_horizon_date_type_key" RENAME TO "event_probabilities_1d_horizon_as_of_date_event_type_key";

ALTER INDEX "analytics"."price_scenarios_1d_horizon_date_axis_name_key" RENAME TO "price_scenarios_1d_horizon_as_of_date_axis_scenario_name_key";

ALTER INDEX "supply"."idx_usda_exports_commodity_date_dest" RENAME TO "usda_exports_1w_event_date_commodity_destination_country_key";

ALTER INDEX "training"."model_runs_run_hash_horizon_days_key" RENAME TO "model_runs_event_run_hash_horizon_days_key";

ALTER INDEX "training"."realized_volatility_symbol_as_of_date_window_days_key" RENAME TO "realized_volatility_1d_symbol_as_of_date_window_days_key";

ALTER INDEX "training"."volatility_surface_underlying_as_of_date_key" RENAME TO "volatility_surface_1d_underlying_as_of_date_key";

-- ---------------------------------------------------------------------------
-- 3. training.matrix_1d: DROP COLUMN + ADD COLUMN (Categories C & D)
--    All SET DATA TYPE clauses excluded.
--    Includes 8 drop+re-add pairs for type changes:
--      hurst_regime, unusual_volume,
--      opt_total_oi_c, opt_total_oi_p,
--      opt_total_volume_c, opt_total_volume_p,
--      opt_avg_premium_c, opt_avg_premium_p
-- ---------------------------------------------------------------------------

ALTER TABLE "training"."matrix_1d"
  -- Pure DROP COLUMN (317 columns removed from schema)
  DROP COLUMN "adx",
  DROP COLUMN "adx_is_missing",
  DROP COLUMN "adx_neg",
  DROP COLUMN "adx_neg_is_missing",
  DROP COLUMN "adx_pos",
  DROP COLUMN "adx_pos_is_missing",
  DROP COLUMN "alma_50",
  DROP COLUMN "alma_50_is_missing",
  DROP COLUMN "atr_14",
  DROP COLUMN "atr_14_is_missing",
  DROP COLUMN "bb_lower",
  DROP COLUMN "bb_lower_is_missing",
  DROP COLUMN "bb_middle",
  DROP COLUMN "bb_middle_is_missing",
  DROP COLUMN "bb_upper",
  DROP COLUMN "bb_upper_is_missing",
  DROP COLUMN "china_pmi_age_days",
  DROP COLUMN "churn_zscore_age_days",
  DROP COLUMN "cmf_21",
  DROP COLUMN "cmf_21_is_missing",
  DROP COLUMN "corr_cpo_30d_age_days",
  DROP COLUMN "corr_cpo_60d_age_days",
  DROP COLUMN "corr_cpo_90d_age_days",
  DROP COLUMN "cpo_atr_ratio_age_days",
  DROP COLUMN "cpo_bb_percent_b_age_days",
  DROP COLUMN "cpo_close_age_days",
  DROP COLUMN "cpo_hurst_exponent_age_days",
  DROP COLUMN "cpo_macd_age_days",
  DROP COLUMN "cpo_returns_1d_age_days",
  DROP COLUMN "cpo_rsi_14_age_days",
  DROP COLUMN "cpo_volume_zscore_age_days",
  DROP COLUMN "cumulative_rsi_is_missing",
  DROP COLUMN "elder_force_index",
  DROP COLUMN "elder_force_index_is_missing",
  DROP COLUMN "fisher_signal",
  DROP COLUMN "fisher_signal_is_missing",
  DROP COLUMN "fisher_transform",
  DROP COLUMN "fisher_transform_is_missing",
  DROP COLUMN "fred_anfci_age_days",
  DROP COLUMN "fred_apu000074714_age_days",
  DROP COLUMN "fred_b235rc1q027sbea_age_days",
  DROP COLUMN "fred_bamlc0a0cm_age_days",
  DROP COLUMN "fred_bamlh0a0hym2_age_days",
  DROP COLUMN "fred_bogmbase_age_days",
  DROP COLUMN "fred_bopgstb_age_days",
  DROP COLUMN "fred_busloans_age_days",
  DROP COLUMN "fred_ccsa_age_days",
  DROP COLUMN "fred_chncpiallminmei_age_days",
  DROP COLUMN "fred_chngdpnqdsmei_age_days",
  DROP COLUMN "fred_chnmainlandtpu_age_days",
  DROP COLUMN "fred_clvmnacscab1gqea19_age_days",
  DROP COLUMN "fred_cpiaucsl_age_days",
  DROP COLUMN "fred_cpilfesl_age_days",
  DROP COLUMN "fred_dcoilbrenteu_age_days",
  DROP COLUMN "fred_dcoilwtico_age_days",
  DROP COLUMN "fred_ddfuelusgulf_age_days",
  DROP COLUMN "fred_dexars_age_days",
  DROP COLUMN "fred_dexbzus_age_days",
  DROP COLUMN "fred_dexcaus_age_days",
  DROP COLUMN "fred_dexchus_age_days",
  DROP COLUMN "fred_dexhkus_age_days",
  DROP COLUMN "fred_dexinus_age_days",
  DROP COLUMN "fred_dexjpus_age_days",
  DROP COLUMN "fred_dexkous_age_days",
  DROP COLUMN "fred_dexmaus_age_days",
  DROP COLUMN "fred_dexmxus_age_days",
  DROP COLUMN "fred_dexnous_age_days",
  DROP COLUMN "fred_dexsfus_age_days",
  DROP COLUMN "fred_dexsius_age_days",
  DROP COLUMN "fred_dexszus_age_days",
  DROP COLUMN "fred_dextaus_age_days",
  DROP COLUMN "fred_dexthus_age_days",
  DROP COLUMN "fred_dexusal_age_days",
  DROP COLUMN "fred_dexuseu_age_days",
  DROP COLUMN "fred_dexusuk_age_days",
  DROP COLUMN "fred_dfedtarl_age_days",
  DROP COLUMN "fred_dfedtaru_age_days",
  DROP COLUMN "fred_dff_age_days",
  DROP COLUMN "fred_dfii10_age_days",
  DROP COLUMN "fred_dfii20_age_days",
  DROP COLUMN "fred_dfii30_age_days",
  DROP COLUMN "fred_dfii5_age_days",
  DROP COLUMN "fred_dfii7_age_days",
  DROP COLUMN "fred_dgasusgulf_age_days",
  DROP COLUMN "fred_dgs10_age_days",
  DROP COLUMN "fred_dgs1_age_days",
  DROP COLUMN "fred_dgs1mo_age_days",
  DROP COLUMN "fred_dgs20_age_days",
  DROP COLUMN "fred_dgs2_age_days",
  DROP COLUMN "fred_dgs30_age_days",
  DROP COLUMN "fred_dgs3mo_age_days",
  DROP COLUMN "fred_dgs5_age_days",
  DROP COLUMN "fred_dgs6mo_age_days",
  DROP COLUMN "fred_dgs7_age_days",
  DROP COLUMN "fred_dhhngsp_age_days",
  DROP COLUMN "fred_dhoilnyh_age_days",
  DROP COLUMN "fred_djfuelusgulf_age_days",
  DROP COLUMN "fred_dprime_age_days",
  DROP COLUMN "fred_dpropanembtx_age_days",
  DROP COLUMN "fred_drcclacbs_age_days",
  DROP COLUMN "fred_dtwexafegs_age_days",
  DROP COLUMN "fred_dtwexbgs_age_days",
  DROP COLUMN "fred_dtwexemegs_age_days",
  DROP COLUMN "fred_dxy_age_days",
  DROP COLUMN "fred_emvtradepolemv_age_days",
  DROP COLUMN "fred_eputrade_age_days",
  DROP COLUMN "fred_expch_age_days",
  DROP COLUMN "fred_expgs_age_days",
  DROP COLUMN "fred_fedfunds_age_days",
  DROP COLUMN "fred_frgshpusm649ncis_age_days",
  DROP COLUMN "fred_gasdesw_age_days",
  DROP COLUMN "fred_gasregw_age_days",
  DROP COLUMN "fred_gdp_age_days",
  DROP COLUMN "fred_gdpc1_age_days",
  DROP COLUMN "fred_gvzcls_age_days",
  DROP COLUMN "fred_houst_age_days",
  DROP COLUMN "fred_icsa_age_days",
  DROP COLUMN "fred_impch_age_days",
  DROP COLUMN "fred_impgs_age_days",
  DROP COLUMN "fred_indpro_age_days",
  DROP COLUMN "fred_ir3tib01cnm156n_age_days",
  DROP COLUMN "fred_lvxrnsa_age_days",
  DROP COLUMN "fred_m2sl_age_days",
  DROP COLUMN "fred_manemp_age_days",
  DROP COLUMN "fred_mortgage30us_age_days",
  DROP COLUMN "fred_myagm2cnm189n_age_days",
  DROP COLUMN "fred_nasdaqcom_age_days",
  DROP COLUMN "fred_nfci_age_days",
  DROP COLUMN "fred_nyfed_bgcr_age_days",
  DROP COLUMN "fred_nyfed_effr_age_days",
  DROP COLUMN "fred_nyfed_obfr_age_days",
  DROP COLUMN "fred_nyfed_sofr_age_days",
  DROP COLUMN "fred_nyfed_tgcr_age_days",
  DROP COLUMN "fred_ovxcls_age_days",
  DROP COLUMN "fred_payems_age_days",
  DROP COLUMN "fred_pbarlusdm_age_days",
  DROP COLUMN "fred_pce_age_days",
  DROP COLUMN "fred_pcepi_age_days",
  DROP COLUMN "fred_pcepilfe_age_days",
  DROP COLUMN "fred_pcoppusdm_age_days",
  DROP COLUMN "fred_pcu311224311224_age_days",
  DROP COLUMN "fred_pcu32411032411012_age_days",
  DROP COLUMN "fred_permit_age_days",
  DROP COLUMN "fred_pmaizmtusdm_age_days",
  DROP COLUMN "fred_pngaseuusdm_age_days",
  DROP COLUMN "fred_polvoilusdm_age_days",
  DROP COLUMN "fred_ppiaco_age_days",
  DROP COLUMN "fred_ppifgs_age_days",
  DROP COLUMN "fred_ppifis_age_days",
  DROP COLUMN "fred_ppoilusdm_age_days",
  DROP COLUMN "fred_pricenpqusdm_age_days",
  DROP COLUMN "fred_proilusdm_age_days",
  DROP COLUMN "fred_psoilusdm_age_days",
  DROP COLUMN "fred_psoybusdm_age_days",
  DROP COLUMN "fred_psugaisausdm_age_days",
  DROP COLUMN "fred_psunousdm_age_days",
  DROP COLUMN "fred_pwheamtusdm_age_days",
  DROP COLUMN "fred_rrpontsyd_age_days",
  DROP COLUMN "fred_rsxfs_age_days",
  DROP COLUMN "fred_sofr_age_days",
  DROP COLUMN "fred_sp500_age_days",
  DROP COLUMN "fred_stlfsi4_age_days",
  DROP COLUMN "fred_stlfsi_age_days",
  DROP COLUMN "fred_t10y2y_age_days",
  DROP COLUMN "fred_t10y3m_age_days",
  DROP COLUMN "fred_t10yie_age_days",
  DROP COLUMN "fred_t20yiem_age_days",
  DROP COLUMN "fred_t30yiem_age_days",
  DROP COLUMN "fred_t5yie_age_days",
  DROP COLUMN "fred_t5yifr_age_days",
  DROP COLUMN "fred_tedrate_age_days",
  DROP COLUMN "fred_totresns_age_days",
  DROP COLUMN "fred_umcsent_age_days",
  DROP COLUMN "fred_unrate_age_days",
  DROP COLUMN "fred_usepuindxd_age_days",
  DROP COLUMN "fred_usepuindxm_age_days",
  DROP COLUMN "fred_vixcls_age_days",
  DROP COLUMN "fred_vxgscls_age_days",
  DROP COLUMN "fred_vxvcls_age_days",
  DROP COLUMN "fred_walcl_age_days",
  DROP COLUMN "fred_wpu01830161_age_days",
  DROP COLUMN "fred_wpu01830171_age_days",
  DROP COLUMN "fred_wpu057303_age_days",
  DROP COLUMN "fred_wpu06140341_age_days",
  DROP COLUMN "fred_wresbal_age_days",
  DROP COLUMN "fred_xtexva01cnm667s_age_days",
  DROP COLUMN "fred_xtimva01cnm667s_age_days",
  DROP COLUMN "fx_aud_usd",
  DROP COLUMN "fx_aud_usd_is_missing",
  DROP COLUMN "fx_brl_usd",
  DROP COLUMN "fx_brl_usd_is_missing",
  DROP COLUMN "fx_cad_usd",
  DROP COLUMN "fx_cad_usd_is_missing",
  DROP COLUMN "fx_chf_usd",
  DROP COLUMN "fx_chf_usd_is_missing",
  DROP COLUMN "fx_cny_usd",
  DROP COLUMN "fx_cny_usd_is_missing",
  DROP COLUMN "fx_eur_usd",
  DROP COLUMN "fx_eur_usd_is_missing",
  DROP COLUMN "fx_gbp_usd",
  DROP COLUMN "fx_gbp_usd_is_missing",
  DROP COLUMN "fx_hkd_usd",
  DROP COLUMN "fx_hkd_usd_is_missing",
  DROP COLUMN "fx_inr_usd",
  DROP COLUMN "fx_inr_usd_is_missing",
  DROP COLUMN "fx_krw_usd",
  DROP COLUMN "fx_krw_usd_is_missing",
  DROP COLUMN "fx_mxn_usd",
  DROP COLUMN "fx_mxn_usd_is_missing",
  DROP COLUMN "fx_myr_usd",
  DROP COLUMN "fx_myr_usd_is_missing",
  DROP COLUMN "fx_nok_usd",
  DROP COLUMN "fx_nok_usd_is_missing",
  DROP COLUMN "fx_nzd_usd",
  DROP COLUMN "fx_nzd_usd_age_days",
  DROP COLUMN "fx_nzd_usd_is_missing",
  DROP COLUMN "fx_sek_usd",
  DROP COLUMN "fx_sek_usd_is_missing",
  DROP COLUMN "fx_sgd_usd",
  DROP COLUMN "fx_sgd_usd_is_missing",
  DROP COLUMN "fx_thb_usd",
  DROP COLUMN "fx_thb_usd_is_missing",
  DROP COLUMN "fx_twd_usd",
  DROP COLUMN "fx_twd_usd_is_missing",
  DROP COLUMN "fx_usd_cny",
  DROP COLUMN "fx_usd_cny_is_missing",
  DROP COLUMN "fx_usd_jpy",
  DROP COLUMN "fx_usd_jpy_is_missing",
  DROP COLUMN "fx_usdzar_age_days",
  DROP COLUMN "fx_zar_usd",
  DROP COLUMN "fx_zar_usd_age_days",
  DROP COLUMN "fx_zar_usd_is_missing",
  DROP COLUMN "hma_20",
  DROP COLUMN "hma_20_is_missing",
  DROP COLUMN "is_crush_season",
  DROP COLUMN "is_crush_season_is_missing",
  DROP COLUMN "is_harvest_season",
  DROP COLUMN "is_harvest_season_is_missing",
  DROP COLUMN "is_planting_season",
  DROP COLUMN "is_planting_season_is_missing",
  DROP COLUMN "is_south_america_harvest",
  DROP COLUMN "is_south_america_harvest_is_missing",
  DROP COLUMN "mcginley_dynamic",
  DROP COLUMN "mcginley_dynamic_is_missing",
  DROP COLUMN "month_cos",
  DROP COLUMN "month_cos_is_missing",
  DROP COLUMN "month_sin",
  DROP COLUMN "month_sin_is_missing",
  DROP COLUMN "news_count",
  DROP COLUMN "news_count_age_days",
  DROP COLUMN "news_count_is_missing",
  DROP COLUMN "obv",
  DROP COLUMN "obv_is_missing",
  DROP COLUMN "oi_delta_zscore_age_days",
  DROP COLUMN "opt_atm_iv",
  DROP COLUMN "opt_avg_gamma_c",
  DROP COLUMN "opt_avg_gamma_p",
  DROP COLUMN "opt_avg_iv_c",
  DROP COLUMN "opt_avg_iv_p",
  DROP COLUMN "opt_avg_theta_c",
  DROP COLUMN "opt_avg_theta_p",
  DROP COLUMN "opt_avg_vega_c",
  DROP COLUMN "opt_avg_vega_p",
  DROP COLUMN "opt_iv_skew",
  DROP COLUMN "opt_put_call_oi_ratio",
  DROP COLUMN "opt_put_call_vol_ratio",
  DROP COLUMN "opt_weighted_delta_c",
  DROP COLUMN "opt_weighted_delta_p",
  DROP COLUMN "rapeseed_close_age_days",
  DROP COLUMN "rin_d3_age_days",
  DROP COLUMN "schaff_trend_cycle",
  DROP COLUMN "schaff_trend_cycle_is_missing",
  DROP COLUMN "si_atr_ratio",
  DROP COLUMN "si_atr_ratio_is_missing",
  DROP COLUMN "si_bb_percent_b",
  DROP COLUMN "si_bb_percent_b_is_missing",
  DROP COLUMN "si_close",
  DROP COLUMN "si_close_is_missing",
  DROP COLUMN "si_hurst_exponent",
  DROP COLUMN "si_hurst_exponent_is_missing",
  DROP COLUMN "si_macd",
  DROP COLUMN "si_macd_is_missing",
  DROP COLUMN "si_returns_1d",
  DROP COLUMN "si_returns_1d_is_missing",
  DROP COLUMN "si_rsi_14",
  DROP COLUMN "si_rsi_14_is_missing",
  DROP COLUMN "si_volume_zscore",
  DROP COLUMN "si_volume_zscore_is_missing",
  DROP COLUMN "stoch_d",
  DROP COLUMN "stoch_d_is_missing",
  DROP COLUMN "stoch_k",
  DROP COLUMN "stoch_k_is_missing",
  DROP COLUMN "sunflower_close_age_days",
  DROP COLUMN "target_price_126d",
  DROP COLUMN "target_price_21d",
  DROP COLUMN "target_price_5d",
  DROP COLUMN "target_price_63d",
  DROP COLUMN "ttm_squeeze_momentum",
  DROP COLUMN "ttm_squeeze_momentum_is_missing",
  DROP COLUMN "ttm_squeeze_on",
  DROP COLUMN "usda_zl_exports_age_days",
  DROP COLUMN "usda_zl_net_sales_age_days",
  DROP COLUMN "usda_zl_outstanding_age_days",
  DROP COLUMN "usda_zm_exports_age_days",
  DROP COLUMN "usda_zm_net_sales_age_days",
  DROP COLUMN "usda_zm_outstanding_age_days",
  DROP COLUMN "usda_zs_exports_age_days",
  DROP COLUMN "usda_zs_net_sales_age_days",
  DROP COLUMN "usda_zs_outstanding_age_days",
  DROP COLUMN "volume_ma_5d_age_days",
  DROP COLUMN "wasde_soybeans_crush_age_days",
  DROP COLUMN "week_of_year_cos",
  DROP COLUMN "week_of_year_cos_is_missing",
  DROP COLUMN "week_of_year_sin",
  DROP COLUMN "week_of_year_sin_is_missing",
  DROP COLUMN "zl_cl_ratio_zscore_age_days",
  DROP COLUMN "zl_zs_ratio_zscore_age_days",
  -- Type-change drops (8 columns: drop old type, re-add with new type below)
  DROP COLUMN "hurst_regime",
  DROP COLUMN "unusual_volume",
  DROP COLUMN "opt_total_oi_c",
  DROP COLUMN "opt_total_oi_p",
  DROP COLUMN "opt_total_volume_c",
  DROP COLUMN "opt_total_volume_p",
  DROP COLUMN "opt_avg_premium_c",
  DROP COLUMN "opt_avg_premium_p",
  -- New ADD COLUMN (57 new columns)
  ADD COLUMN     "_hurst_regime_raw" TEXT,
  ADD COLUMN     "board_crush_expanding" BIGINT,
  ADD COLUMN     "board_crush_expanding_is_missing" BIGINT,
  ADD COLUMN     "board_crush_zscore_252d" DOUBLE PRECISION,
  ADD COLUMN     "board_crush_zscore_252d_is_missing" BIGINT,
  ADD COLUMN     "close_is_missing" BIGINT,
  ADD COLUMN     "crack_321" DOUBLE PRECISION,
  ADD COLUMN     "crack_321_is_missing" BIGINT,
  ADD COLUMN     "crack_321_zscore" DOUBLE PRECISION,
  ADD COLUMN     "crack_321_zscore_is_missing" BIGINT,
  ADD COLUMN     "diesel_crack_wide" BIGINT,
  ADD COLUMN     "diesel_crack_wide_is_missing" BIGINT,
  ADD COLUMN     "ema_100" DOUBLE PRECISION,
  ADD COLUMN     "ema_200" DOUBLE PRECISION,
  ADD COLUMN     "ema_21" DOUBLE PRECISION,
  ADD COLUMN     "ema_50" DOUBLE PRECISION,
  ADD COLUMN     "fx_usdhkd" DOUBLE PRECISION,
  ADD COLUMN     "fx_usdhkd_is_missing" BIGINT,
  ADD COLUMN     "fx_usdinr" DOUBLE PRECISION,
  ADD COLUMN     "fx_usdinr_is_missing" BIGINT,
  ADD COLUMN     "fx_usdmyr" DOUBLE PRECISION,
  ADD COLUMN     "fx_usdmyr_is_missing" BIGINT,
  ADD COLUMN     "fx_usdnok" DOUBLE PRECISION,
  ADD COLUMN     "fx_usdnok_is_missing" BIGINT,
  ADD COLUMN     "fx_usdsek" DOUBLE PRECISION,
  ADD COLUMN     "fx_usdsek_is_missing" BIGINT,
  ADD COLUMN     "fx_usdthb" DOUBLE PRECISION,
  ADD COLUMN     "fx_usdthb_is_missing" BIGINT,
  ADD COLUMN     "fx_usdtwd" DOUBLE PRECISION,
  ADD COLUMN     "fx_usdtwd_is_missing" BIGINT,
  ADD COLUMN     "high_is_missing" BIGINT,
  ADD COLUMN     "ho_crack" DOUBLE PRECISION,
  ADD COLUMN     "ho_crack_is_missing" BIGINT,
  ADD COLUMN     "ho_crack_zscore_63d" DOUBLE PRECISION,
  ADD COLUMN     "ho_crack_zscore_63d_is_missing" BIGINT,
  ADD COLUMN     "hurst_regime_is_missing" BIGINT,
  ADD COLUMN     "low_is_missing" BIGINT,
  ADD COLUMN     "open_interest_is_missing" BIGINT,
  ADD COLUMN     "open_is_missing" BIGINT,
  ADD COLUMN     "opt_avg_premium_c_is_missing" BIGINT,
  ADD COLUMN     "opt_avg_premium_p_is_missing" BIGINT,
  ADD COLUMN     "opt_total_oi_c_is_missing" BIGINT,
  ADD COLUMN     "opt_total_oi_p_is_missing" BIGINT,
  ADD COLUMN     "opt_total_volume_c_is_missing" BIGINT,
  ADD COLUMN     "opt_total_volume_p_is_missing" BIGINT,
  ADD COLUMN     "rb_crack" DOUBLE PRECISION,
  ADD COLUMN     "rb_crack_is_missing" BIGINT,
  ADD COLUMN     "target_ret_126d" DOUBLE PRECISION,
  ADD COLUMN     "target_ret_21d" DOUBLE PRECISION,
  ADD COLUMN     "target_ret_5d" DOUBLE PRECISION,
  ADD COLUMN     "target_ret_63d" DOUBLE PRECISION,
  ADD COLUMN     "unusual_volume_is_missing" BIGINT,
  ADD COLUMN     "volume_is_missing" BIGINT,
  ADD COLUMN     "zl_cpo_spread" DOUBLE PRECISION,
  ADD COLUMN     "zl_cpo_spread_is_missing" BIGINT,
  ADD COLUMN     "zl_cpo_spread_zscore" DOUBLE PRECISION,
  ADD COLUMN     "zl_cpo_spread_zscore_is_missing" BIGINT,
  -- Type-change re-adds (8 columns with new types)
  ADD COLUMN     "hurst_regime" BIGINT,
  ADD COLUMN     "unusual_volume" BIGINT,
  ADD COLUMN     "opt_total_oi_c" DOUBLE PRECISION,
  ADD COLUMN     "opt_total_oi_p" DOUBLE PRECISION,
  ADD COLUMN     "opt_total_volume_c" DOUBLE PRECISION,
  ADD COLUMN     "opt_total_volume_p" DOUBLE PRECISION,
  ADD COLUMN     "opt_avg_premium_c" DOUBLE PRECISION,
  ADD COLUMN     "opt_avg_premium_p" DOUBLE PRECISION;
